#!/bin/bash
# aur-build - build packages to a local repository
[[ -v AUR_DEBUG ]] && set -o xtrace
set -o errexit
shopt -s extglob
argv0=build
startdir=$PWD
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default options
chroot=0 no_sync=0 overwrite=0 sign_pkg=0 run_pkgver=0 results=0 prefix=aur

# default arguments
chroot_args=()
gpg_args=(--detach-sign --no-armor --batch)
makepkg_args=()
makechrootpkg_args=(-cu)
repo_add_args=()

db_replaces() {
    bsdcat "$1" | awk '
    /%REPLACES%/ {
        while(NF != 0) { getline; print; }
    }'
}

trap_exit() {
    if [[ ! -v AUR_DEBUG ]]; then
        rm -rf "$tmp"
        # Only remove package directory if all files were moved (#593)
        rm -df "$var_tmp"
    else
        printf >&2 'AUR_DEBUG: %s: temporary files at %s\n' "$argv0" "$tmp"
        printf >&2 'AUR_DEBUG: %s: temporary files at %s\n' "$argv0" "$var_tmp"
    fi
}

usage() {
    plain 'usage: %s [-acfBNS] [-d repo] [--root path] [--] <makepkg args>' "$argv0" >&2
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh
source /usr/share/makepkg/util/parseopts.sh

if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
    [[ -t 2 ]] && colorize
fi

# mollyguard for makepkg
if (( UID == 0 )) && [[ ! -v AUR_ASROOT ]]; then
    warning 'aur-%s is not meant to be run as root.' "$argv0"
    warning 'To proceed anyway, set the %s variable.' 'AUR_ASROOT'
    exit 1
fi

## option parsing
opt_short='a:B:d:D:AcCfnrsvLNRST'
opt_long=('arg-file:' 'chroot' 'database:' 'force' 'root:' 'sign'
          'verify' 'directory:' 'no-sync' 'pacman-conf:' 'results:'
          'makepkg-conf:' 'remove' 'build-command:' 'pkgver' 'rmdeps'
          'noconfirm' 'ignorearch' 'log' 'new' 'bind:' 'bind-rw:'
          'prevent-downgrade' 'temp' 'syncdeps' 'clean' 'multilib')
opt_hidden=('dump-options')

if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

unset build_cmd db_name db_path db_root pacman_conf makepkg_conf results_file queue
while true; do
    case "$1" in
        # build options
        -a|--arg-file)
            shift; queue=$1 ;;
        -B|--build-command)
            shift; build_cmd+=("$1") ;;
        -f|--force)
            overwrite=1 ;;
        -c|--chroot)
            chroot=1 ;;
        -d|--database)
            shift; db_name=$1 ;;
        --makepkg-conf)
            shift; makepkg_conf=$1 ;;
        --pacman-conf)
            shift; pacman_conf=$1 ;;
        -N|--nosync|--no-sync)
            no_sync=1 ;;
        --pkgver)
            run_pkgver=1
            makepkg_args+=(--holdver) ;;
        --results)
            shift; results_file=$1 ;;
        --root)
            shift; db_root=$1 ;;
        -S|--sign|--gpg-sign)
            sign_pkg=1
            repo_add_args+=(-s) ;;
        # chroot options
        -D|--directory)
            shift; makechrootpkg_args+=(-r "$1") ;;
        --bind)
            shift; makechrootpkg_args+=(-D "$1") ;;
        --bind-rw)
            shift; makechrootpkg_args+=(-d"$1") ;;
        --prefix)
            shift; prefix=$1 ;;
        -T|--temp)
            makechrootpkg_args+=(-T) ;;
        # makepkg options
        -A|--ignorearch|--ignore-arch)
            makepkg_args+=(--ignorearch) ;;
        -C|--clean)
            makepkg_args+=(--clean) ;;
        -L|--log)
            makepkg_args+=(--log) ;;
        -n|--noconfirm|--no-confirm)
            makepkg_args+=(--noconfirm) ;;
        -r|--rmdeps)
            makepkg_args+=(--rmdeps) ;;
        -s|--syncdeps)
            makepkg_args+=(--syncdeps) ;;
        # repo-add options
        -v|--verify)
            repo_add_args+=(-v) ;;
        -R|--remove)
            repo_add_args+=(-R) ;;
        --new)
            repo_add_args+=(-n) ;;
        --prevent-downgrade)
            repo_add_args+=(-p) ;;
        # other options
        --dump-options)
            printf -- '--%s\n' "${opt_long[@]}"
            printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g'
            exit ;;
        --) shift; break ;;
    esac
    shift
done

tmp=$(mktemp -d --tmpdir "aurutils-$argv0.XXXXXXXX") || exit
var_tmp=$(mktemp -d --tmpdir="${TMPDIR:-/var/tmp/}" "aurutils-$argv0.XXXXXXXX") || exit

trap 'trap_exit' EXIT
trap 'exit' INT

if (( chroot )); then
    # Default to /usr/share/devtools/pacman-<prefix>.conf
    chroot_args+=(--prefix "$prefix")

    if [[ -v pacman_conf ]];then
        chroot_args+=(--pacman-conf "$pacman_conf")
    fi
    if [[ -v makepkg_conf ]]; then
        chroot_args+=(--makepkg-conf "$makepkg_conf")
    fi
fi

# Append remaining options to make{,chroot}pkg command-line
makepkg_args+=("$@")
makechrootpkg_args+=("$@")

# Assign environment variables (#443)
: "${db_name=$AUR_REPO}"
: "${db_root=$AUR_DBROOT}"
: "${pacman_conf=/etc/pacman.conf}"

# Automatically choose repository root and name based on pacman
# configuration and user environment.
if [[ -z $db_name ]] && [[ -z $db_root ]]; then
    db_path=$(aur repo --pacman-conf "$pacman_conf")
    db_root=$(dirname "$db_path")
    db_name=$(basename "$db_path" .db)

elif [[ -z $db_name ]] && [[ -n $db_root ]]; then
    error '%s: root specified without database name' "$argv0"
    exit 1

elif [[ -n $db_name ]] && [[ -z $db_root ]]; then
    db_path=$(aur repo --pacman-conf "$pacman_conf" -d "$db_name")
    db_root=$(dirname "$db_path")

elif [[ -n $db_name ]] && [[ -n $db_root ]]; then
    db_path=$db_root/$db_name.db
fi

# Resolve symbolic link to database.
if ! db_path=$(readlink -e -- "$db_path"); then
    error '%s: %s: No such file or directory' "$argv0" "$db_path"
    exit 2
fi

if ! [[ -w $db_path ]]; then
    error '%s: %s: Permission denied' "$argv0" "$db_path"
    exit 13
fi

# Write successfully built packages to file (#437)
if [[ -v results_file ]]; then
    : >"$results_file" # truncate file
    results=1
fi

if (( chroot )); then
    # Update pacman and makepkg configuration for the chroot build
    # queue. A full system upgrade is run on the /root container to
    # avoid lenghty upgrades for makechrootpkg -cu.
    aur chroot --no-build "${chroot_args[@]}"
else
    # Configuration for host builds.
    { printf '[options]\n'
      pacconf --raw --options --config "$pacman_conf"

      printf '[%s]\n' "$db_name"
      pacconf --raw --repo="$db_name" --config "$pacman_conf"
    } > "$tmp"/custom.conf
fi

if [[ -v queue ]]; then
    exec {fd}< "$queue"
else
    exec {fd}< <(printf '\n')
fi

if (( sign_pkg )); then
    if [[ -v GPGKEY ]]; then
        gpg --list-keys "$GPGKEY"
        gpg_args+=(-u "$GPGKEY")
    fi
else
    db_sigs=("$db_root/$db_name".sig
             "$db_root/$db_name".files.sig)

    if [[ -f ${db_sigs[0]} ]]; then
        error '%s: database signature found, but signing is disabled' "$argv0"

        printf '%q\n' >&2 "${db_sigs[@]}"
        exit 1
    fi
fi

# PKGDEST defined here is NOT exported to the build environment.
# This is not a concern for container builds, as makechrootpkg
# already has a similar mechanism for defining PKGDEST. (#498)
{ if [[ -v makepkg_conf ]]; then
      cat -s "$makepkg_conf"
  else
      # Write makepkg configuration in the order as parsed by makepkg,
      # see /usr/share/makepkg/util/config.sh
      cat -s /etc/makepkg.conf

      if [[ -r $XDG_CONFIG_HOME/pacman/makepkg.conf ]]; then
          cat -s "$XDG_CONFIG_HOME"/pacman/makepkg.conf
      elif [[ -r $HOME/.makepkg.conf ]]; then
          cat -s "$HOME"/.makepkg.conf
      fi
  fi

  printf "PKGDEST='%s'\\n" "$var_tmp"
} >"$tmp"/makepkg.conf

# PKGDEST set in the environment takes precedence over PKGDEST set in
# makepkg.conf (#513)
unset PKGDEST

while IFS= read -ru "$fd" path; do
    cd_safe "$startdir/$path"

    # Run pkgver before --packagelist (#500)
    if (( run_pkgver )); then
        # Ignore architecture in pkgver() function (#536)
        makepkg --noprepare -od --ignorearch
    fi

    if (( ! overwrite )); then
        unset mark

        while IFS= read -r; do
            [[ -f $REPLY ]] && mark+=("$REPLY")
        done < <(PKGDEST="$db_root" makepkg --packagelist)

        if [[ ${mark[*]} ]]; then
            warning '%s: skipping built package (use -f to overwrite)' "$argv0"

            printf '%q\n' >&2 "${mark[@]}"
            continue
        fi
    fi

    if [[ -v build_cmd ]]; then
        printf '%s\n' >&2 "Running custom command: ${build_cmd[*]}"
        env PKGDEST="$var_tmp" AUR_REPO="$db_name" AUR_DBROOT="$db_root" "${build_cmd[@]}"
    elif (( chroot )); then
        env PKGDEST="$var_tmp" aur chroot --no-prepare "${chroot_args[@]}" \
            -- "${makechrootpkg_args[@]}"
    else
        printf '%s\n' >&2 "Running makepkg ${makepkg_args[*]}"
        makepkg --config "$tmp"/makepkg.conf "${makepkg_args[@]}"
    fi

    cd_safe "$var_tmp"
    pkglist=(!(*.sig)) # discard makepkg --sign from package list (#410)
    siglist=()

    # pkglist should not be empty (#513)
    if [[ ${pkglist[*]} == '!(*.sig)' ]]; then
        error '%s: invalid argument (no packages found)' "$argv0"
        exit 22
    fi

    for p in "${pkglist[@]}"; do
        if [[ -f $p.sig ]]; then
            warning '%s: existing package signature found' "$argv0"
            siglist+=("$p".sig)

        elif (( sign_pkg )); then
            gpg "${gpg_args[@]}" --output "$p".sig "$p"
            siglist+=("$p".sig)
        fi
    done

    # Move build products (relative paths)
    mv -f "${pkglist[@]}" "${siglist[@]}" "$db_root"

    # Update database
    cd_safe "$db_root"
    LANG=C repo-add "${repo_add_args[@]}" "$db_path" "${pkglist[@]}"

    if (( results )); then
        printf "build:file://${db_path%/*}/%s\n" "${pkglist[@]}" | tee -a "$results_file"
    fi

    if (( chroot )) || (( no_sync )); then
        continue
    else
        replaces=$(grep -Fxf <(db_replaces "$db_path") <(pacman -Qq) | paste -s -d, -)

        sudo pacman -Fy  --config="$tmp"/custom.conf
        sudo pacman -Syu --config="$tmp"/custom.conf --ignore="$replaces" --noconfirm
    fi
done

exec {fd}<&-

# vim: set et sw=4 sts=4 ft=sh:
