#!/bin/bash
# aur-chroot - build packages with systemd-nspawn
[[ -v AUR_DEBUG ]] && set -o xtrace
set -o errexit
readonly argv0=chroot
readonly PATH=/bin:/usr/bin
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

machine=$(uname -m)
readonly machine

# default arguments (machine-dependent)
chroot_prefix=extra
directory=/var/lib/aurbuild/$machine
makepkg_conf=/usr/share/devtools/makepkg-$machine.conf

# default options
prepare=1 build=1 create=0 

usage() {
    printf >&2 'usage: %s [-d repo] [-CDM path] -- <makechrootpkg args>\n' "$argv0"
    exit 1
}

source /usr/share/makepkg/util/parseopts.sh

opt_short='cuTC:M:'
opt_long=('directory:' 'pacman-conf:' 'makepkg-conf:' 'no-build'
          'no-prepare' 'create' 'prefix:' 'bind:' 'bind-ro:' 'clean'
          'update' 'temp')
opt_hidden=('dump-options' 'nobuild' 'noprepare')

if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

unset bindmounts_ro cache_dirs makechrootpkg_args pacman_conf
while true; do
    case "$1" in
        --create)
            create=1 ;;
        --prefix)
            chroot_prefix=$1 ;;
        --no-build|--nobuild)
            build=0 ;;
        --no-prepare|--noprepare)
            prepare=0 ;;
        # arch-nspawn options
        -D|--directory)
            shift; directory=$1 ;;
        -C|--pacman-conf)
            shift; pacman_conf=$1 ;;
        -M|--makepkg-conf)
            shift; makepkg_conf=$1 ;;
        # makechrootpkg options
        -c|--clean)
            makechrootpkg_args+=(-c) ;;
        -u|--update)
            makechrootpkg_args+=(-u) ;;
        -T|--temp)
            makechrootpkg_args+=(-T) ;;
        --bind)
            shift; makechrootpkg_args+=(-d "$1") ;;
        --bind-ro)
            shift; makechrootpkg_args+=(-D "$1") ;;
        --dump-options)
            printf -- '--%s\n' "${opt_long[@]}" ;
            printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g' ;
            exit ;;
        --) shift; break ;;
    esac
    shift
done

if (( $# )); then
    makechrootpkg_args=("$@")
fi

# pacman configuration
case $chroot_prefix in
    multilib*)
        base_packages=('multilib-devel') ;;
    *)
        base_packages=('base-devel') ;;
esac
pacman_conf=${pacman_conf:-/usr/share/devtools/pacman-$chroot_prefix.conf}

# bind mount file:// paths to container (#461)
while read -r key _ value; do
    case $key=$value in
        Server=file://*)
            bindmounts_ro+=("${value#file://}") ;;
    esac
done < <(pacman-conf --config "$pacman_conf")

if (( create )); then
    # parent path is not created by mkarchroot (#371)
    if [[ ! -d $directory ]]; then
        sudo install -d "$directory" -m 755 -v
    fi

    sudo mkarchroot -C "$pacman_conf" -M "$makepkg_conf" \
         "$directory"/root "${base_packages[@]}"
    exit 0
fi

if (( prepare )); then
    # locking is done by systemd-nspawn
    sudo arch-nspawn -C "$pacman_conf" -M "$makepkg_conf" "$directory"/root \
         "${bindmounts_ro[@]/#/--bind-ro=}" pacman -Syu --noconfirm
fi

if (( build )); then
    sudo --preserve-env=GNUPGHOME,PKGDEST makechrootpkg -r "$directory" \
         "${bindmounts_ro[@]/#/-D}" "${makechrootpkg_args[@]}"
fi

# vim: set et sw=4 sts=4 ft=sh:
